version: '3.8'

services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: rigel_electronic_cloud
      POSTGRES_USER: rkrigelsoft
      POSTGRES_PASSWORD: "Rk!@#121"
    volumes:
      - /data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    image: eclipse-temurin:17-jdk
    container_name: user_service_core
    depends_on:
      - db
    volumes:
      - /home/ubuntu/rigelworkspace/user-service/todoapp.jar:/app.jar
    command: ["java", "-jar", "/app.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rigel_electronic_cloud
      SPRING_DATASOURCE_USERNAME: rkrigelsoft
      SPRING_DATASOURCE_PASSWORD: "Rk!@#121"
    ports:
      - "8089:8089"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge