version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: rigel_electronic_cloud
      POSTGRES_USER: rkrigelsoft
      POSTGRES_PASSWORD: "Rk!@#121"
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: spring-backend
    restart: always
    ports:
      - "8089:8089"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rigel_electronic_cloud
      SPRING_DATASOURCE_USERNAME: rkrigelsoft
      SPRING_DATASOURCE_PASSWORD: "Rk!@#121"

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "8091:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend

volumes:
  pgdata: